"""
Sentinel Grading Harness (grader.py)
------------------------------------
Scores candidate reconciliation reports against ground truth datasets.

Usage:
  python grader.py --datasets ./data/dirty --reports ./reports --out ./results
"""

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Dict, List, Any

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("sentinel.grader")

@dataclass_stub # For conceptual clarity
class ScoreCard:
    precision: float = 0.0
    recall: float = 0.0
    f1: float = 0.0
    impact_accuracy: float = 0.0
    evidence_score: float = 0.0
    total_score: float = 0.0

def load_json(path: Path) -> Dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))

def score_dataset_01_04(report: Dict, truth: Dict) -> Dict:
    """Exact matching strategy for baseline and complex datasets."""
    expected = truth.get("expected_flags", [])
    detected = report.get("flags", [])
    
    tp = 0
    fp = 0
    impact_diff = 0.0
    evidence_hits = 0
    total_evidence_possible = 0
    
    # Map for matching
    truth_map = { (f["sku"], f["type"]): f for f in expected }
    
    for d_flag in detected:
        key = (d_flag.get("sku"), d_flag.get("ghost_type") or d_flag.get("type"))
        if key in truth_map:
            tp += 1
            exp_flag = truth_map[key]
            
            # 1. Financial Impact Check ($0.01 tolerance)
            d_impact = float(d_flag.get("financial_impact_usd") or d_flag.get("impact", 0))
            e_impact = float(exp_flag.get("impact", 0))
            if abs(d_impact - e_impact) <= 0.01:
                impact_diff += 0 # Perfect match
            else:
                impact_diff += abs(d_impact - e_impact)
                
            # 2. Evidence Chain check
            exp_evidence = exp_flag.get("evidence", [])
            det_evidence = d_flag.get("evidence_chain") or d_flag.get("source_citations", [])
            
            total_evidence_possible += len(exp_evidence)
            for e_ev in exp_evidence:
                # Basic check: file + line match
                match = any(
                    (str(d_ev.get("file")).endswith(e_ev["file"]) and 
                     int(d_ev.get("line_number") or d_ev.get("line_hint") or 0) == e_ev["line"])
                    for d_ev in det_evidence
                )
                if match:
                    evidence_hits += 1
            
            del truth_map[key]
        else:
            fp += 1
            
    fn = len(truth_map)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    
    return {
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4),
        "evidence_accuracy": round(evidence_hits / total_evidence_possible, 4) if total_evidence_possible > 0 else 1.0,
        "impact_variance": round(impact_diff, 2)
    }

def score_dataset_05(report: Dict, truth: Dict) -> Dict:
    """Approximate count scoring for scale dataset."""
    expected_counts = truth.get("summary_counts", {})
    detected_flags = report.get("flags", [])
    
    det_counts = {}
    for f in detected_flags:
        t = f.get("ghost_type") or f.get("type")
        det_counts[t] = det_counts.get(t, 0) + 1
        
    # Variance per type
    variances = {}
    for t, exp_c in expected_counts.items():
        det_c = det_counts.get(t, 0)
        variances[t] = abs(det_c - exp_c) / exp_c if exp_c > 0 else 0
        
    avg_error = sum(variances.values()) / len(variances) if variances else 0
    accuracy = max(0, 1 - avg_error)
    
    return {
        "scale_accuracy": round(accuracy, 4),
        "f1": round(accuracy, 4), # Mapping accuracy to f1 for summary
        "notes": "Dataset 05 uses approximate count scoring."
    }

def generate_markdown(results: Dict) -> str:
    md = "# 🏆 Sentinel Grading Summary\n\n"
    md += "| Dataset | F1 Score | Recall | Precision | Status |\n"
    md += "|---------|----------|--------|-----------|--------|\n"
    
    for ds, res in results.items():
        status = "✅ PASS" if res.get("f1", 0) > 0.9 else "❌ FAIL"
        md += f"| {ds} | {res.get('f1')} | {res.get('recall')} | {res.get('precision')} | {status} |\n"
        
    md += "\n\n_Generated by Sentinel Grading Harness v0.1_"
    return md

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--datasets", required=True, help="Path to dirty datasets folder")
    p.add_argument("--reports",  required=True, help="Path to candidate reports folder")
    p.add_argument("--out",      default="./results", help="Output directory")
    args = p.parse_args()

    out_path = Path(args.out)
    out_path.mkdir(parents=True, exist_ok=True)
    
    dataset_path = Path(args.datasets)
    report_path = Path(args.reports)
    
    final_results = {}
    
    # Process Datasets 01 - 05
    for i in range(1, 6):
        ds_name = f"dataset_{i:02d}"
        if i == 5:
            ds_name = "dataset_05_scale_10k"
        else:
            # Handle potential name variations
            matches = list(dataset_path.glob(f"dataset_{i:02d}*"))
            if matches:
                ds_name = matches[0].name
            else:
                continue

        truth = load_json(dataset_path / ds_name / "ground_truth.json")
        if not truth and i == 5:
            truth = load_json(dataset_path / ds_name / "ground_truth_summary.json")
            
        report_file = report_path / f"{ds_name}.reconciliation_report.json"
        report = load_json(report_file)
        
        if not report or not truth:
            logger.warning(f"Missing data for {ds_name}, skipping.")
            continue
            
        logger.info(f"Grading {ds_name}...")
        if i == 5:
            final_results[ds_name] = score_dataset_05(report, truth)
        else:
            final_results[ds_name] = score_dataset_01_04(report, truth)
            
    # Write summary
    (out_path / "grade_summary.json").write_text(json.dumps(final_results, indent=2))
    (out_path / "grade_summary.md").write_text(generate_markdown(final_results))
    
    logger.info(f"Grading complete. Results in {args.out}")

if __name__ == "__main__":
    main()
